server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
            - "http://localhost:5173"
            - "http://44.218.147.127:5173"
            - "http://44.218.147.127"
            - "https://gamebakescloud.vercel.app"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: servicio-usuarios-perfil
          uri: "http://servicio-usuarios:8080"
          predicates:
            - Path=/api/usuarios/perfil/**
        - id: servicio-usuarios-publico
          uri: "http://servicio-usuarios:8080"
          predicates:
            - Path=/api/usuarios/**
        - id: servicio-resenas
          uri: "http://servicio-resenas:8081"
          predicates:
            - Path=/api/resenas/**
        - id: servicio-pedidos
          uri: "http://servicio-pedidos:8082"
          predicates:
            - Path=/api/pedidos/**

        - id: servicio-perfil
          uri: "http://servicio-perfil:8084"
          predicates:
            - Path=/api/perfil, /api/perfil/**
        - id: servicio-productos-privado
          uri: "http://servicio-productos:8085"
          predicates:
            - Path=/api/productos/**
            - Method=POST, PUT, PATCH, DELETE
        - id: servicio-productos-publico
          uri: "http://servicio-productos:8085"
          predicates:
            - Path=/api/productos/**
            - Method=GET, OPTIONS
        - id: servicio-pagos
          uri: "http://servicio-pagos:8086"
          predicates:
            - Path=/api/pagos/**