version: '3.8'

services:
  rabbitmq_global:
    image: rabbitmq:3-management
    container_name: rabbitmq_global
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 3s
      retries: 10

  api-gateway:
    build: ./servicios-backend/api-gateway
    container_name: api_gateway
    ports:
      - "9000:9000"

  servicio-usuarios:
    build: ./servicios-backend/servicio-usuarios
    container_name: app_usuarios
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.28.229:3306/gb_usuarios
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  servicio-resenas:
    build: ./servicios-backend/servicio-resenas
    container_name: app_resenas
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.28.229:3306/gb_resenas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  servicio-pedidos:
    build: ./servicios-backend/servicio-pedidos
    container_name: app_pedidos
    ports:
      - "8082:8082"
    depends_on:
      rabbitmq_global:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.28.229:3306/gb_pedidos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq_global

  servicio-perfil:
    build: ./servicios-backend/servicio-perfil
    container_name: app_perfil
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.28.229:3306/gb_perfil
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  servicio-productos:
    build: ./servicios-backend/servicio-productos
    container_name: app_productos
    ports:
      - "8085:8085"
    depends_on:
      rabbitmq_global:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.28.229:3306/gb_productos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq_global

  servicio-pagos:
    build: ./servicios-backend/servicio-pagos
    container_name: app_pagos
    ports:
      - "8086:8086"
    depends_on:
      rabbitmq_global:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.28.229:3306/gb_pagos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq_global

  frontend-react:
    build: ./gamebakes-web
    container_name: app_frontend
    ports:
      - "5173:80"
    depends_on:
      - api-gateway