spring.application.name=servicio-productos
server.port=8085

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-server:3306/gb_productos?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq-server}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.profile.tenant-id=e41697ee-1b10-4b64-95da-b32ec0fdb9a7
spring.cloud.azure.active-directory.credential.client-id=7f32a189-8be6-4f14-92ab-9d8e80fac2bc
spring.cloud.azure.active-directory.app-id-uri=api://7f32a189-8be6-4f14-92ab-9d8e80fac2bc

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/e41697ee-1b10-4b64-95da-b32ec0fdb9a7/v2.0